on:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>Hi there!</h1> Thank you for creating an issue. We appreciate your feedback and will do our best to address your concerns as quickly as possible. If you have any questions or need additional information, please don't hesitate to let us know. Welcome to the community. Thanks again for your contribution!"
          pr-message: "<h1>Thank you for creating a pull request for vibey!</h1> We appreciate your contribution and are excited to review your changes. If you have any questions or need additional information, please don't hesitate to let us know. We look forward to working with you to improve vibey. Thanks again for your support!"
          footer: 'If you want to keep contributing to open source and want to do it with a supportive and inclusive community, consider joining <a href="https://github.com/UniKonf">UniKonf</a>. We help and encourage each other to make regular contributions to open source projects. If you have any questions, do not hesitate to ask. We look forward to having you as part of our community!'
